export const CREATE_CONTACT_REQUEST = "CREATE_CONTACT_REQUEST";
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const CREATE_CONTACT_FAIL = "CREATE_CONTACT_FAIL";
export const ALL_CONTACT_REQUEST = "ALL_CONTACT_REQUEST";
export const ALL_CONTACT_SUCCESS = "ALL_CONTACT_SUCCESS";
export const ALL_CONTACT_FAIL = "ALL_CONTACT_FAIL";
export const CONTACT_DETAILS_REQUEST = "CONTACT_DETAILS_REQUEST";
export const CONTACT_DETAILS_SUCCESS = "CONTACT_DETAILS_SUCCESS";
export const CONTACT_DETAILS_FAIL = "CONTACT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CONTACT_SUBMIT";
