export const CREATE_QUESTION_REQUEST = "CREATE_QUESTION_REQUEST";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAIL = "CREATE_QUESTION_FAIL";
export const ALL_QUESTION_REQUEST = "ALL_QUESTION_REQUEST";
export const ALL_QUESTION_SUCCESS = "ALL_QUESTION_SUCCESS";
export const ALL_QUESTION_FAIL = "ALL_QUESTION_FAIL";
export const UPDATE_ANSWERS_REQUEST = "UPDATE_ANSWERS_REQUEST";
export const UPDATE_ANSWERS_SUCCESS = "UPDATE_ANSWERS_SUCCESS";
export const UPDATE_ANSWERS_FAIL = "UPDATE_ANSWERS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
